# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b47528549d5c6f85fb4b0abd6919b49ed20d0034f0167c98dfd09a8bfd0e207f22d047e27103b2a1f055e7160c12be8c25c367bcedbf92b526501d0dd686a1a3

test:
  secret_key_base: 08bfc570a1902b2c785ccd129a655f4c39391546bea48a4fe9d1fe3f2b476db8011cfc09de110aa4962eafd274cdd35b280837f08c1e71ecc840390c3bf06202

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
